### ISSUE TITLE
SDL Issue?

### ISSUE THREAD

**Issue by Gloomshroud** [tome2/tome2#28]
I'm not sure if this is intentional, but when running with ./src/tome-sdl on Ubuntu 18.04, I do not get any subwindows in my main window (as you would in say, Angband). Is this by design? I recall in the original ToME available with apt install it is the same. I downloaded and compiled this version hoping the SDL implementation would be feature complete. This is no criticism, I'm just trying to see where we're at. :) 

At any rate, I've run it default (./src/tome-sdl) and with suboptions (/tome-sdl -- -n3) to no avail. Could totally be user error. Thanks in advance for any light you can shed!

**Comment by BardurArantsson** [comment]
I'm not sure, but IIRC the SDL port does its own window handling and it might very well be the case that e.g. "-n3" doesn't actually work correctly. I seem to recall that there's some sort of key/menu you can access which allows you to resize/reconfigure/etc. the windows *inside* the SDL frontend. (I believe this is because SDL 1.x didn't actually support showing multiple separate windows on the screen.)

In general I've found the SDL port to be pretty awful, and I'd recommend using the X11 frontend instead. 

(I've been dabbling a little bit with implementing an SDL2.x frontend and removing all the other frontends since SDL2.x can basically do all the things, but I wouldn't hold my breath... :smile: )

**Comment by Gloomshroud** [comment]
Yes, the X11 front end is what I generally use to play. It is beautiful and crisp and easily legible anyway. I was just playing around with the SDL (after seeing what the new SDL does in Angband 4.1.2). This is by far my favorite *band variant, and my favorite ToME egine. Thank you for your work. If I knew the first thing, I'd pitch in. I'll go ahead and close this, but I'll keep an eye for that port in future. Thanks again for keeping this alive! :dagger:
