### ISSUE TITLE
Stack overflow when stepping onto a "cobblestone road" tile with GCC

### ISSUE THREAD

**Issue by jkatzmewing** [tome2/tome2#36]
When compiled with GCC 7.3.0 or 8.2.0, stepping onto a "cobblestone road" tile crashes the game immediately.

ASAN output (with GCC 7.3.0):

```
=================================================================
==29603==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7fffffffc9a8 at pc 0x5555577639db bp 0x7fffffffc8c0 sp 0x7fffffffc8b0
READ of size 8 at 0x7fffffffc9a8 thread T0
    #0 0x5555577639da in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::_M_swap(std::__shared_count<(__gnu_cxx::_Lock_policy)2>&) /usr/include/c++/7/bits/shared_ptr_base.h:712
    #1 0x5555581a85c0 in std::__shared_ptr<monster_race const, (__gnu_cxx::_Lock_policy)2>::__shared_ptr(std::__shared_ptr<monster_race const, (__gnu_cxx::_Lock_policy)2>&&) /usr/include/c++/7/bits/shared_ptr_base.h:1133
    #2 0x5555581a6732 in std::shared_ptr<monster_race const>::shared_ptr(std::shared_ptr<monster_race const>&&) /usr/include/c++/7/bits/shared_ptr.h:245
    #3 0x5555581a48a7 in _FUN<std::shared_ptr<const monster_race> > src/cave.cc:1251
    #4 0x555558189938 in map_info_layer3 src/cave.cc:1088
    #5 0x55555818c36f in map_info src/cave.cc:1262
    #6 0x55555818defa in lite_spot(int, int) src/cave.cc:1478
    #7 0x555557c6635c in update_mon(int, char) src/monster2.cc:1760
    #8 0x555557c67a15 in update_monsters(char) src/monster2.cc:1882
    #9 0x5555580dd3e0 in update_stuff() src/xtra1.cc:4041
    #10 0x55555784ad81 in dungeon src/dungeon.cc:4477
    #11 0x55555784e7df in play_game src/dungeon.cc:4846
    #12 0x5555576c2b48 in main_real src/main.cc:262
    #13 0x5555576c1723 in main src/main-sdl.c:2101
    #14 0x7ffff46efb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #15 0x5555576b10d9 in _start (/home/melpomene/tome2/tome-sdl+0x215d0d9)

Address 0x7fffffffc9a8 is located in stack of thread T0 at offset 40 in frame
    #0 0x5555581a47c6 in _FUN<std::shared_ptr<const monster_race> > src/cave.cc:1246

  This frame has 2 object(s):
    [32, 40) '<unknown>' <== Memory access at offset 40 overflows this variable
    [96, 112) '<unknown>'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /usr/include/c++/7/bits/shared_ptr_base.h:712 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::_M_swap(std::__shared_count<(__gnu_cxx::_Lock_policy)2>&)
Shadow bytes around the buggy address:
  0x10007fff78e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff78f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007fff7930: f1 f1 f1 f1 00[f2]f2 f2 f2 f2 f2 f2 00 00 f2 f2
  0x10007fff7940: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007fff7950: 00 00 f1 f1 f1 f1 01 f2 f2 f2 f2 f2 f2 f2 01 f2
  0x10007fff7960: f2 f2 f2 f2 f2 f2 02 f2 f2 f2 f2 f2 f2 f2 02 f2
  0x10007fff7970: f2 f2 f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00
  0x10007fff7980: f2 f2 f2 f2 f2 f2 00 00 f2 f2 f2 f2 f2 f2 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==29603==ABORTING
[Inferior 1 (process 29603) exited with code 01]
```

**Comment by BardurArantsson** [comment]
Hm, any particular place you were doing this? Is it reliably reproducible for you?

Btw, I have quite a bit of private code which is "on top" of the current master -- It's quite conceivable that this is already fixed there (and probably introduced new bugs :smile:). I'll see if I get time to just do minimal clean up and push that to a branch soonish (a few days).

**Comment by jkatzmewing** [comment]
@BardurArantsson 

Where: in Bree at the start of a new game
Reliably reproducible: every time :)

I'm doing some investigation of my own on this, will see where it leads. And ack re the new code.

**Comment by BardurArantsson** [comment]
Ok, so I've got everything rebased, compiling, etc., but I seem to have introduced a segfault even before starting the Game in Theme and almost immediately in the vanilla game. I notice that there are a *lot* of new warnings with the more recent compiler versions, but I didn't notice anything that could obviously be the cause of the crash.

I'll have a go at figuring out where the problem is, etc. and I'll try to push my changes some time next week. (My weekend is already basically gone at this point, so...)

If you feel like having a go at it, I've pushed it to the 'next' branch in this repo.

**Comment by jkatzmewing** [comment]
Okay, thanks! We'll see what I and my flimsy debugging skills and limited time can manage :)

**Comment by BardurArantsson** [comment]
Heh :)

I'm not really sure what's happened, because I'm usually at least playing a *little* bit when I do a series of commits and/or push to GitHub. Of course C++ is a treacherous language and issues may not surface until compilers get "sufficiently smart"...

**Comment by jkatzmewing** [comment]
My guess is that's because you're using Clang, which lately seems either a lot more tolerant of badness or a lot less prone to false alarms. Or maybe both. Or maybe GCC still hasn't fully implemented C++14, IDK. This stuff is all yet another reason I'm learning Rust... But yeah so far none of these crashes occur when compiling with Clang.

Anyway I'll see what next has changed. (In the 15 minutes or so I have before heading off to dinner with friends.)

**Comment by BardurArantsson** [comment]
Yeah, it's frustrating especially when you have such an old code base and have to be able to compile on lots of compilers, etc. etc.

I'm actually doing an experiment on converting the whole thing to Scala/Scala.js, but it's slow going (roughly 70k C++ LoC left, I think my pace is around 250-1000 lines per week). It's very interesting to see, though, just how much simpler a lot of the code could be.

I'm doing a very "literal" translation avoiding the urge to introduce algebraic data types whereever they may be appropriate. So it's *really* ugly Scala currently, but with the much better support for ADTs/pattern matching, interfaces, etc. etc. I think it could be cleaned up a *lot*. Of course some of this would apply in Rust too, but I do find that GC makes this type of thing a lot easier (than C/C++), so it'd be interesting to see.

If I end up abandoning the Scala rewrite, I'll probably go for Rust or a language with full C ABI interop and then to go for a *gradual* rewrite rather than an all-or-nothing. By that time C++23 will probably be out, so who knows... maybe that'll be good enough :)

I do have to say that there's still quite a bit of low-hanging refactoring that could be done in the current C++ code base, but I just tend to feel that I'm fighting the language on simple things like being able to rely on initialization order of globals, having true interfaces, etc.)

**Comment by jkatzmewing** [comment]
Mmm. I spent a bit of time messing around with your older pure C version, seeing if I could move it to using libapr or glib2 - something to at least help abstract out various data types and common operations, and put them on a more solid and portable foundation. Didn't get very far though, it's still a big task, and I'm a newbie with those APIs; plus backporting the nice features from 2.4.x would be quite painful.

**Comment by jkatzmewing** [comment]
This has stopped being an issue as of GCC 9.
