### ISSUE TITLE
Saving&Loading of function key macros don't work.

### ISSUE THREAD

**Issue by Turmfalke2** [tome2/tome2#51]
hi,
I can create a simple macro that turns F1 into another m. This works.
I can then dump the macro to a pref file and I get the following:
```
A:m
P:\[F1]
```
Then after restarting the game and loading the pref file the macro no longer works.
If I dump it again I get the following:
```
A:m
P:^_\r
```

Clearly something is broken here and I am surprised to be first to run into this issue? 

I had a look at the code ( https://github.com/tome2/tome2/blob/5eb341d266bd46e1d28e8effc4864891aeb84b91/src/cmd4.cc#L1405 ), but the comments are more misleading than helpful. Pretty sure in line 1418 it is extracting the trigger and not the action. 

90% of the comments are useless 
```
	/* Close */
	my_fclose(fff);
```
and the other 10% are misleading.

**Comment by Turmfalke2** [comment]
More garbage comments to make reading the code more confusing.

https://github.com/tome2/tome2/blob/5eb341d266bd46e1d28e8effc4864891aeb84b91/src/util.cc#L823

The first comment in text_to_ascii is just copied from ascii_to_text with no regards for what the function is actually supposed to do. More comments does not mean better code!

**Comment by Turmfalke2** [comment]
I think I found where it breaks:

https://github.com/tome2/tome2/blob/002f241dbeb71088d2bcc96696b63b7d2a074e7c/src/util.cc#L761

here it compares str which equals F1] in my example (the [ gets skipped in line 741) with every known keysymbol in macro_trigger_name. However symbols in macro_trigger_name never end with a ], they are just F1,F2,.. so this check always fails. The `&& ']' == str[len]` never matters, because the first check already failed.

**Comment by BardurArantsson** [comment]
I am loath to change any of this because it's incredibly brittle code in general, so the risk of breakage is great.

What I *have* observed is that different platforms have different quirks regarding being able to properly save/load macros.

Can you explain in more detail when exactly you're seeing this, e.g. which platform, is NumLock/ScrollLock or anything like that toggled on/off, etc.?

**Comment by Turmfalke2** [comment]
hi,
I have since revert back back to playing 2.3.5. I found myself disagreeing with most of the newer changes and when I crashed after entering a shop I binned the install.

The fix here should still be pretty strait forward, I suspect the issue was created when converting part of the codebase to c++ and replacing some of the string compare functions with boost calls.

Is there anything specific you don't understand about the patch? It is all about skipping the ] at the end so the string compare with `macro_trigger_name` works.

I am on linux here, with a keyboard that has no numblock. Also I don't think the keyboard affects how the config file gets parsed.

**Comment by BardurArantsson** [comment]
> Also I don't think the keyboard affects how the config file gets parsed.

Indeed not, but it affects exactly get gets generated when you record a macro.... often in surprising ways. The whole system is incredibly brittle -- and not just because of the code. It's at least two layers of 'interpretation' on top of each other. :(

I'll try to reproduce it locally and see. It may take a little while... in the middle of a moving situation and I'm not entirely sure where I have a keyboard with a numpad.

FWIW, I suspect your NumLock is actually set even though you don't have a numpad. It's often the case that it is set as a default. It makes the arrow keys behave differently for T2... otherwise you wouldn't actually be able to use arrows keys to move around in the menus.

**Comment by Turmfalke2** [comment]
I don't use arrows keys, I use the rogue key bindings. 

Also the recording works and I assume the following is a syntactically correct macro. 
```
A:m
P:\[F1]
```

**Comment by BardurArantsson** [comment]
I have now verified that this does indeed fix it (which was expected :) ) and that it -- more importantly -- doesn't seem to break anything else :).

Thanks for the fix!
